### ISSUE TITLE
Automatic Login

### ISSUE THREAD

**Issue by bramski** [angularjs-oauth/oauth-ng#106]
More of a feature request.  For my application, having a "login" button is a bit annoying.  We'd much rather immediately send the user to the oauth provider for login if they aren't logged in.

There is a hackish way to do this it seems...
```
<div class="hidden" ng-if="show == 'logged-out'">
  {{login()}}
</div>
```

**Comment by bramski** [comment]
This can now be dealt with by handling the various broadcasts.

**Comment by verbeeckjan** [comment]
@bramski Can you provide an example please?

**Comment by bramski** [comment]
$ scope.on ('oauth:logged-out', -> Endpoint.login ())

**Comment by bramski** [comment]
Apologies for the shorthand example.  Drinking wine in my kitchen and on my phone.

**Comment by verbeeckjan** [comment]
Thank you, I was unaware that there was a factory called Endpoint. Also in version v0.4.2, which I was using it doesn't have a login function yet.
