### ISSUE TITLE
Error thrown by cancelExpiresAtEvent function

### ISSUE THREAD

**Issue by mike-tempest** [angularjs-oauth/oauth-ng#126]
cancelExpiresAtEvent uses $timeout, but it is not injected into the AccessToken factory causing a block error to be thrown.

Easy way of replicating error being thrown is run AccessToken.setTokenFromString(hash). I have created a pr for the fix as this is blocking us from a release of a new oauth integration in our app.

PR for fix
https://github.com/angularjs-oauth/oauth-ng/pull/125

**Comment by mike-tempest** [comment]
@m00s would be good to get this in soon

**Comment by m00s** [comment]
Hi @mike-tempest, the same fix was merged with the PR #124. 
I just released v0.4.9

Closing this
