### ISSUE TITLE
what value to put in pub key?

### ISSUE THREAD

**Issue by baywet** [angularjs-oauth/oauth-ng#139]
Hi,
I'm a little unclear on what to put in the pub-key value.
In my scenario I'm authenticating against a identity server 4.
Here is one of my token as an example
`eyJhbGciOiJSUzI1NiIsImtpZCI6Ijk0MjgxODU4YTY4YjZkYTU1YTNmZjllM2FmZGQ3NDExYzI3ODc0ZmFjMWJjOWFlNTFlMDYzODM2NDIxYjg4MzIiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE0NzYyODQwMzQsImV4cCI6MTQ3NjI4NDMzNCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzODQiLCJhdWQiOiJqcyIsIm5vbmNlIjoiZHVtbXlub25jZSIsImlhdCI6MTQ3NjI4NDAzNCwiYXRfaGFzaCI6IjluV3JPTWlJS0tZTTJ5SVcwTmVuR1EiLCJzaWQiOiJlZjYzYjg2M2ViZjQ4MDUzMTYzZDdkYzliODEzODkzMDIxMDdlMjNjYzEyNGQ3NDNjYTM2NGE1YmQzMWRhNmE1Iiwic3ViIjoiNzdhNDNlNTYyMGNkNWFlNDA2MDhlNTNmMGMzNTYxMDU1NzU1ZTMyZTQ3Yzg1NDllNDFlMGFjMzU4MGNkNjllOSIsImF1dGhfdGltZSI6MTQ3NjI4MDA2MSwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvN2QzYmMxYzQtNzkwMy00MWRkLWI0YmQtZGFiYzUzNzY5ZDZkLyIsImFtciI6WyJleHRlcm5hbCJdfQ.WjnfU28MMgBgIZqKpCgWzh-b2PjKM0VBGNP3Vf42J8pGb8NeFzNUnujIIRYtujFHRDSii8NHYSH0mvYiZCLDCgJEQenjm9AhNKBlm8EaSt-NRsEnTF5dPyVk4bbVyFiXD9sbitmtPW7ziMcq-XNffSNhnUa5AlLw4e_CRLNQcSFyEb3-HotdOB21O9j0ofzxjqd3ZykjXHtS-bIIqico3sVETINt2mUB49zw6GNeyK73_uxidiv_aiqvR7ciO-5zdUrC_YDRBFFP2esVBLvr37F-vvwx6XcMPGq_wGSFmr3h-li3g8xs6ZSgtvgNE-Ebmyi2mIAhgJ4d3nDbWpFYmg`  

Here is my configuration
`<oauth`  
`site="https://localhost:44384"`  
`client-id="js"`  
`redirect-uri="http://localhost:3000/"`  
`profile-uri="https://localhost:44384/connect/userinfo"`  
`scope='openid profile email api1'`  
`authorize-path="/connect/authorize?nonce=dummynonce"`  
`response-type="id_token token"`  
`pub-key="f83f57ecf10160f4de91394e91af98070edb642153131960e6519cf5694da7ef">`  
`</oauth>`  

and here is what I have in my well known configuration openid-configuration/kwks
`{"keys":[{"kty":"RSA","use":"sig","kid":"f83f57ecf10160f4de91394e91af98070edb642153131960e6519cf5694da7ef","e":"AQAB","n":"weN1_y7wDK3cDziG7myVfa-pNSJrWrxJ368TzOwX2sUVWNGw8pKQyA5y1yzkyTeldvGUkdoEfGzZUcP5LtyRqtJsbr4cfMF36pRBpvfCd_NR2ArKKdXT_xOwgPfZGdUuajMMShSsYeiAZKeOL6KzgQ5jIUxnED_8m2oe0Jb5XY4Ojmz17_ONfZrdengwDxtGbhcDPzSRwFJ0YmnHYNDHGTnFFEG7o4XyZ2jEX7NW0z-9RhIGCkh_AVAAOai7LaNQLGAswmQpb3l6TH6xRt57lCEKcvIp1n95hIlPSpWpyoBpIWfxvMcyaBDj_xGl4NZ16G0HrN6ANnvZ-D-tQD79ew"}]}`  

Thanks for your help!

**Comment by baywet** [comment]
After digging around in the code, the ietf, and a few other resources (I'll  list those bellow) I  found that it's actually either expecting:
- jwk from the header of the token (not present in my case)
- the whole .wellknownconfiguration (with the keys directly referenced, no urls) in the local storage
- the key (take the whole json entry, without the keys collection, from the jwks_uri) in  the pub-key.

It could use some better documentation.
It'd be awesome if this component could go read the wellknownconfig and the jwks_uri automatically

**Comment by baywet** [comment]
Documentation used to determine that https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-26#page-9  
https://tools.ietf.org/html/rfc7517#appendix-A   
http://openid.net/specs/openid-connect-core-1_0.html#ImplicitIDTValidation   
https://connect2id.com/blog/how-to-validate-an-openid-connect-id-token

**Comment by baywet** [comment]
Digging a little more in the code the library supports it, you just have to specify the issuer and the wellKnown="true" (not documented).
The only trick is that wellKnown is always undefinied line 307 which causes the whole "go get the keys" process to fail. Maybe @jimmytheneutrino can fix that for us?

**Comment by baywet** [comment]
After further investigation I found that the setting is actually well-Known (with a dash) and then everything works properly. That should be documented. I might submit a PR to document it.

**Comment by jimmytheneutrino** [comment]
Sorry for neglecting this thread. I did not understand what the problem was at first glance and did not have time to dive in to research it. 

This is the standard angular 1.x normalization between parameters and attributes: https://docs.angularjs.org/guide/directive#normalization

A PR for documentation would be great! 
Info is here: https://github.com/angularjs-oauth/oauth-ng/pull/114

There is also an example configuration of urlRouterProvider to support non-html5 mode.
