### ISSUE TITLE
google+ problem

### ISSUE THREAD

**Issue by davidsoderberg** [angularjs-oauth/oauth-ng#55]
``` html
<oauth
    template="template.html"
    site="https://accounts.google.com/o/oauth2/auth"
        client-id="my_client_id"
    redirect-uri="my_redirect_url"
    profile-uri="http://www.googleapis.com/plus/v1/people/me"
    scope="openid email">
</oauth>
```

Hi, can anybody help to get it  right with google+, why does the code above dont work?

**Comment by airtonix** [comment]
- the values for `scope` will looke more like uris than simple words.
- to get the user profile from google, you need to supply the proper scopes
- to be able to use those scopes, you need to enable them in your [api developer console](https://console.developers.google.com/)


further reading:
- https://developers.google.com/drive/web/scopes
- https://developers.google.com/gmail/api/auth/scopes
- https://developers.google.com/+/web/api/rest/oauth
- https://developers.google.com/+/web/people/
- https://developers.google.com/google-apps/spreadsheets/#authorizing_requests_with_oauth_20
- https://developers.google.com/web/

Hope this helps.
