### ISSUE TITLE
Expose the ability to update token expiry

### ISSUE THREAD

**Issue by rsouthgate** [angularjs-oauth/oauth-ng#74]
I'm using openAM as an oauth2 server. It provides the ability to retrieve token info after a token has been supplied to the client. The client calls an api service periodically that is the resource granted by the token. That api also provides the Bearer token found in the headers of the request to thje openAM oauth server which has a 'keepalive' and therefore updates the expiry of the session on the server.

The client can subsequently call an openAM tokeninfo endpoint to get a new expiry time. I would like to be able to update the AccessToken service so that it can update the token from this json object.

Any reason why I shouldn't do this?

**Comment by bramski** [comment]
PR: https://github.com/angularjs-oauth/oauth-ng/pull/116
